packages:
  - '.'
allowBuilds:
  '@nestjs/core': set this to true or false
  '@openapitools/openapi-generator-cli': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
